### ISSUE TITLE
Does Kalends/DateTime.now/1 handle DST?

### ISSUE THREAD

**Issue by hahuang65** [lau/calendar#1]
Just needed to know if I do something like

`"America/Los_Angeles" |> Kalends.DateTime.now`

Will I need to handle DST on my own?

**Comment by lau** [comment]
Hi. Yes, it will handle DST.

Some more details and explanation: You will get back for instance:

``` elixir
%Kalends.DateTime{abbr: "PDT", day: 2, hour: 18, min: 58, month: 4, sec: 4,
 std_off: 3600, timezone: "America/Los_Angeles", usec: 570505, utc_off: -28800,
 year: 2015}
```

When you call the `now` function, Kalends gets finds out what "UTC offset" and "standard offset" is in place. In this case the offset from UTC is -28800 seconds (8 hours). That's the `utc_off` part of the struct. `std_off` is 3600 which is 3600 seconds (1 hour). `std_off` is the offset from standard time and is what is used for DST.

If you pipe it to the rfc3339 formatting function you can see that the total UTC offset is -7 (minus 8 plus 1 hour of DST).:
`"America/Los_Angeles" |> Kalends.DateTime.now |> Kalends.DateTime.Format.rfc3339`
`"2015-04-02T19:06:49.590458-07:00"`

If you do `Kalends.DateTime.from_erl! {{2015, 2, 1}, {0, 0, 0}}, "America/Los_Angeles"` which represents midnight on the Feb 1st 2015, you get:

``` elixir
%Kalends.DateTime{abbr: "PST", day: 1, hour: 0, min: 0, month: 2, sec: 0,
 std_off: 0, timezone: "America/Los_Angeles", usec: nil, utc_off: -28800,
 year: 2015}
```

Because DST is not in used in February in Los Angeles, `std_off` is 0 in that case.

Feel free to ask any other questions, I'm happy to help.

**Comment by hahuang65** [comment]
Thanks for the explanation :)

**Comment by lau** [comment]
You're welcome :)
