### ISSUE TITLE
use Calendar is deprecated

### ISSUE THREAD

**Issue by Cifer-Y** [lau/calendar#27]
In readme, the use macro section, I think I can use `use Calendar`.
But that will get a warning: `warning: use Calendar is deprecated!`.
So, should I use `use Calendar`?

**Comment by lau** [comment]
Short answer: Don't use `use Calendar`.

Explanation: It is deprecated, so in future versions it will be removed. So instead of having to change the code when you upgrade to a newer version of Elixir and Calendar, it would be advantageous to stop using `use Calendar` now.

And also it would be best to not use `alias` for e.g. `Calendar.DateTime`. What `use Calendar` does is basically just aliasing various Calendar modules.

The reason for getting rid of `use Calendar` is: In Elixir 1.3 there will be modules with structs called Date, DateTime, NaiveDateTime, Time. So if `Calendar.Date` is aliased for `Date`, the two module names will conflict.

**Comment by Cifer-Y** [comment]
@lau OK, Thanks for the clear explanition. I got it. I just curioused why it deprecated but still in the README.md.

**Comment by lau** [comment]
@Cifer-Y Good point. I had removed other references to `use Calendar` from the readme, but missed that one. Now that section is removed from the readme. Thanks.
