### ISSUE TITLE
Parsing DateTimes with timezone info

### ISSUE THREAD

**Issue by mgwidmann** [lau/calendar#39]
I'm not sure what format this is in (which by the way makes this library very hard to use) but I cannot get this datetime to parse without supplying the timezone information...

```elixir
# Successfully parses
Calendar.DateTime.Parse.rfc3339("2016-12-09T11:06:56.451-05:00", "America/New_York")

# How can I do this?
Calendar.DateTime.Parse.would_prefer_a_magical_parse_all_helper("2016-12-09T11:06:56.451-05:00")
```

But the information of the timezone is right there `-05:00`, so I don't want to supply `"America/New_York"` when I could be wrong, forcing me to have to look at that and basically parse this date myself.

**Comment by lau** [comment]
A DateTime needs a proper time zone identifier. RFC3339 does not have that, it only has an offset. So it is impossible to know if it is New York or not.

You could use `Calendar.DateTime.Parse.rfc3339_utc("2016-12-09T11:06:56.451-05:00")` to get 
```elixir
{:ok,
 %DateTime{calendar: Calendar.ISO, day: 9, hour: 16, microsecond: {0, 0}, minute: 6, month: 12, second: 56, std_offset: 0, time_zone: "Etc/UTC",
  utc_offset: 0, year: 2016, zone_abbr: "UTC"}}
```

Notice that this gets the time in UTC which is 16:06, not 11:06. To get the local time you can use a NaiveDateTime:

```elixir
Calendar.NaiveDateTime.Parse.iso8601("2016-12-09T11:06:56.451-05:00")
{:ok, ~N[2016-12-09 11:06:56.451], -18000}
```

The issue is that RFC3339 does not have the information of which timezone it is. An offset (-5 hours) is not the same as a time zone such as America/New_York

**Comment by mgwidmann** [comment]
Ok thanks, its hard to know what parser to use since most people are not familiar with the rfc specs... Would be nice if it was just `DateTime.parse` like it is in Ruby...

**Comment by lau** [comment]
In Elixir 1.4 ISO-8601 parsing will be built in and works in a similar way: https://github.com/elixir-lang/elixir/commit/1ff7a42ab11ff791e5d0d0644344df02ba785a0b

In Elixir 1.4 the function name in `DateTime` will be `from_iso8601` though. So the same as for `NaiveDateTime`.

The way it works in Ruby has its problems.
