### ISSUE TITLE
Issue with timezone conversion

### ISSUE THREAD

**Issue by ijunaid8989** [lau/calendar#55]
```elixir
iex(6)> {:ok, mvd } = Calendar.DateTime.from_erl {{2014,10,4},{23,44,32}}, "Etc/UTC"
{:ok, #DateTime<2014-10-04 23:44:32Z>}
iex(7)> mvd |> Calendar.DateTime.shift_zone!("Europe/London")
#DateTime<2014-10-05 00:44:32+01:00 BST Europe/London>
iex(8)> mvd |> Calendar.DateTime.shift_zone!("Europe/Dublin")
#DateTime<2014-10-04 23:44:32+00:00 GMT Europe/Dublin>
iex(9)> 
```
There is some issue in changing timezone when its Dublin, there is one hour difference between UTC and Dublin time but conversion is not adding day light saving.

Can you guide?

**Comment by ijunaid8989** [comment]
Its working fine in calendar repo but not when included in my project
```elixir
iex(6)> {:ok, mvd } = Calendar.DateTime.from_erl {{2014,10,4},{23,44,32}}, "Etc/UTC"
{:ok, #DateTime<2014-10-04 23:44:32Z>}
iex(7)> mvd |> Calendar.DateTime.shift_zone!("Europe/Dublin")                       
#DateTime<2014-10-05 00:44:32+01:00 IST Europe/Dublin>
iex(8)> 
```

we have timex in the project that could be a problem?

Also in Calendar repo after shift zone, it gives `IST Europe/Dublin>`

but in our application after shift zone it gives `GMT Europe/Dublin` why?

**Comment by lau** [comment]
Hi. Thank you for the report. I can confirm that there is an issue with how `Europe/Dublin` is handled. There is an issue with how the period builder handles that zone. It looks like the problem was introduced in version 0.5.17. Using 0.5.16 should calculate the Dublin time zone correctly.

You could specify tzdata version 0.5.16 `{:tzdata, "0.5.16", override: true}` for now. Once there is a newer version out with the problem solved, I will let you know.

**Comment by lau** [comment]
Hi @ijunaid8989 

A new version `0.5.19` has been released which fixes the problem with the Dublin time zone.
