### ISSUE TITLE
Shift Zone treats "UTC" and "Etc/UTC" differently

### ISSUE THREAD

**Issue by benwilson512** [lau/calendar#60]
Elixir 1.9.1
calendar 1.0.0
tzdata 1.0.1

```
iex(19)> ~U[2019-11-09 02:18:56Z] |> Calendar.DateTime.shift_zone("Etc/UTC")
{:ok, ~U[2019-11-09 02:18:56Z]}
iex(20)> ~U[2019-11-09 02:18:56Z] |> Calendar.DateTime.shift_zone("UTC")    
{:ok, #DateTime<2019-11-09 02:18:56+00:00 UTC UTC>}
```

This causes issues because the to_string representation then reads `2019-11-09 02:18:56+00:00 UTC UTC`

**Comment by lau** [comment]
Hi Ben.

That string representation is defined in Elixir, not Calendar.

"UTC" is linked to "Etc/UTC" as a kind of alias. In the same way that "Europe/Isle_of_Man" is linked to "Europe/London".

If you created a DateTime for "Europe/Isle_of_Man" and got one back with "Europe/London" instead of "Europe/Isle_of_Man" I don't think that would be good. I would prefer not to make a special case in the code for "UTC" -> "Etc/UTC" making it work differently.

`UTC` as a time zone name is a special case because both the time zone name and abbreviation are the same. Also it is in the `backzone` file:

> This file provides links between current names for timezones
> and their old names.  Many names changed in late 1993.

Meaning that the current name for the UTC time zone in the tz database is `Etc/UTC`. I like `Etc/UTC` over `UTC` as a time zone identifier because it makes it different from the abbreviation and looks similar to other time zones with city or country names. Even though it is more characters to type.

Why not use just "Etc/UTC" instead of "UTC"? What kind of issues do you see? Is it other people's data that contains the "UTC" string? Maybe you could have a filter that transforms "UTC" to "Etc/UTC" some time before passing it along to `shift_zone`.

**Comment by benwilson512** [comment]
Hi @lau I don't have an issue using `"Etc/UTC"`, but the thing is that the list of zones from Tzdata includes both. I don't want to special case "UTC" either, I'd prefer to drive it all off of what Tzdata provides and assumed that libraries that derive timezone handling from Tzdata would follow aliases if that was what aliases are supposed to do.

Perhaps I'm simply misunderstanding the representation though. When I do:

```
iex(5)> DateTime.utc_now |> Calendar.DateTime.shift_zone!("America/New_York") |> to_string
"2019-11-11 17:07:46.355623-05:00 EST America/New_York"
```
I am surprised to see both EST and America/New_York. In the case of UTC I guess both of those are UTC which is why it's repeated. In either case, we moved to NimbleStrftime for displaying datetimes and %Z gives me what I expect, so perhaps I was relying on something I should not have.

**Comment by benwilson512** [comment]
In rereading your answer though you make a good point WRT that both the inspect and string representations come from Elixir itself. I think I'm barking up the wrong tree in general.

**Comment by lau** [comment]
> I am surprised to see both EST and America/New_York.

Both are in the struct. What you see depends on how you view the struct. I would not show the users the default struct representation in most cases. I don't think it was ever meant for that.

Calendar has Strftime that uses the `zone_abbr` field for `%Z`. If you want the `time_zone` name that is a string in the struct.

> would follow aliases if that was what aliases are supposed to do

The aliases work as intended. They are really supposed to be more of an internal thing. For instance Isle of Man has the same rules as London, but if it changes in the future it could stop linking to London.

If you are interested you can read more about it in the files here https://data.iana.org/time-zones/releases/tzdb-2019c.tar.lz

Are you showing users a dropdown where they can choose time zones? With all the almost 600 zones? That could work in some cases, but for that you might want to exclude certain ones.
Like the ones in `backward`: ` Tzdata.zone_list -- Tzdata.zone_lists_grouped[:backward]`. 

Or maybe use something like this that I just put together: https://github.com/lau/friendly_time_zone_list

In that a user can see "UTC" but it is mapped to "Etc/UTC".

I hope this helps.
